### ISSUE TITLE
Docker-compose breaks

### ISSUE THREAD

**Issue by mihai-mc** [GhermanClaudiu/TemplateNavSideBar#2]
Docker compose breaks due to misconfig

**Comment by GhermanClaudiu** [comment]
buna Mihai se pare ca am un bag in componeta Supervizor.jsx am implementat useHttp custom hook si ceva nu functioneaza, nu stiu daca ai tipm sa te uiti dar eu nu am gsit o solutie.

Multumesc
    On Sunday, April 7, 2024 at 09:40:09 PM GMT+3, Mihai-Cristian Olteanu ***@***.***> wrote:  
 
 


Docker compose breaks due to misconfig

**Comment by mihai-mc** [comment]
Te rog deschide un nou issue in care sa descrii ce nu merge. O sa fac merge la [PR#1](https://github.com/GhermanClaudiu/TemplateNavSideBar/pull/1), deci nu uita sa rulezi `git pull`

**Comment by mihai-mc** [comment]
Issue closed by [PR#1](https://github.com/GhermanClaudiu/TemplateNavSideBar/pull/1)
